-- What is checkout?
-- This is a pending order created by the user.
-- This happens after the clicks checkout and waiting for payment
-- So record should be remove after payment success

CREATE TABLE public.checkout (
    checkout_id    BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id        UUID        REFERENCES auth.users(id),
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    status         VARCHAR(10) DEFAULT 'pending',

    -- please do note that, these info below about the product
    -- should generated by the server side
    -- products
    products JSONB  DEFAULT '[]',      -- { product_id, quantity }
    total_amount    NUMERIC DEFAULT 0,
    discount        NUMERIC DEFAULT 0,
    discount_amount NUMERIC DEFAULT 0,
    grand_total     NUMERIC DEFAULT 0,

   -- user information
   name          VARCHAR(255),
   email         VARCHAR(255),
   contact       VARCHAR(255),
   address       VARCHAR(255),
   delivery_note TEXT,
   notes         TEXT
);

ALTER TABLE public.checkout ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only see their own checkout data"
ON public.checkout
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can only update their own checkout data"
ON public.checkout
FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can only insert their own checkout data"
ON public.checkout
FOR INSERT
WITH CHECK (auth.uid() = user_id); 

